# Generated by Django 4.2.2 on 2023-07-02 13:29

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_alter_products_id_alter_variation_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=80)),
                ("image_url", models.ImageField(upload_to=store.models.upload_to)),
            ],
        ),
    ]
