# Generated by Django 4.2.2 on 2023-07-02 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_mymodel_prediction_alter_mymodel_device_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="mymodel",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2023, 7, 2, 18, 15, 26, 551537),
            ),
            preserve_default=False,
        ),
    ]
